### PR TITLE
Clarify temporary need to use empty passphrases with on-disk keys

### PR DESCRIPTION
**Pull request by nealmcb**
See also: #360

### CODE REVIEW

**Comment by adityasaky** [comment]
@nealmcb, do you mind if I add this proposed text as part of #385? I made this text bold, and I can sneak this in as well with you listed as a coauthor.

**Comment by adityasaky** [comment]
https://github.com/gittuf/gittuf/pull/385/commits/c03a42b14aa7766a0acd918f0cdca86a320117a9

**Comment by adityasaky** [comment]
Incorporated (and released!) in #385. Thank you!

**Comment by nealmcb** [comment]
That's fine. Looks good!

**Pull request closed without merging**
